id: bat
name: bat
description: Cat clone with syntax highlighting and Git integration
homepage: https://github.com/sharkdp/bat
tags:
  - cli
  - file-viewer
dependencies: []
versionCommand: bat --version
versionParseRegex: "bat (\\d+\\.\\d+\\.\\d+)"
require-sudo: true
steps:
  - name: Install bat
    type: brew
    command: bat
    platforms:
      - darwin
  - name: Install bat (Linux)
    type: apt
    command: bat
    platforms:
      - linux

